refactor!: set no open source license value to 0
SchwarzIT/go-template pull request #60
Opened 2021-11-05 10:00 UTC by linuxluigi

Set no open source license value to 0 instead of 9.

2021-11-05 14:46 UTC, brumhard requested changes
Pls don't include the ci options

2022-01-21 12:34 UTC, linuxluigi commented
CI options are removed.

2022-01-28 14:53 UTC, brumhard commented
Could you also remove the ci options in the example testdata/values file pls?

2022-02-04 14:04 UTC, brumhard approved these changes

2022-02-04 14:06 UTC, merged